openapi: 3.0.0
info:
  title: Vet Appointment API
  version: 1.0.0
  description: API for managing vet appointments
servers:
  - url: http://localhost:3001
paths:
  /api/appointments:
    post:
      summary: Create a new appointment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: "Pet's name"
                phoneNumber:
                  type: string
                  description: "Phone number"
                ownerName:
                  type: string
                  description: "Owner's name"
                appointmentDate:
                  type: string
                  format: date
                  description: "Appointment date (YYYY-MM-DD)"
      responses:
        '201':
          description: Appointment created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Appointment created successfully
        '400':
          description: Invalid request payload
        '500':
          description: Server error
